# Generated by Django 5.0 on 2023-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
